### ISSUE TITLE
Did not work for pd.corr (calculating correlation matrix)

### ISSUE THREAD

**Issue by mikbuch** [dubovikmaster/parallel-pandas#4]
I used the example from the README, just wanted to parallelize calculating correlations in a large dataframe. Unfortunately, it did not work.

**Comment by dubovikmaster** [comment]
Hello!
Yes, because this method doesn't support at this time. Unfortunately

**Comment by dubovikmaster** [comment]
When I was developing this module, I did some experiments with the corr method and I was not able to get any significant results, unfortunately
Tell me what size is your dataframe?

**Comment by mikbuch** [comment]
@dubovikmaster , thank your for the reply. Maybe it is a good idea to add a disclaimer to the README specifying what panda's functions are supported by the parallelization, and which are not, this way people would not try to use it in vein :)
The size of my dataframe is ~5k rows and ~ 3k columns but there will be more rows in the future. Now it is still not worth for me to write/experiment more with parallelization, but if it comes to a point when I really need it, we can cooperate on adding this feature. I did some parallelization in the past in MPI for HPC, and with `multiprocessing` in Python, so maybe I can provide you with some fresh insight on why it does not work properly for the `pd.corr` function.

**Comment by mikbuch** [comment]
Btw., are you living in Warsaw now? Nice :) I'm from Poznan

**Comment by mikbuch** [comment]
> > @dubovikmaster , thank your for the reply. Maybe it is a good idea to add a disclaimer to the README specifying what panda's functions are supported by the parallelization, and which are not, this way people would not try to use it in vein :) The size of my dataframe is ~5k rows and ~ 3k columns but there will be more rows in the future. Now it is still not worth for me to write/experiment more with parallelization, but if it comes to a point when I really need it, we can cooperate on adding this feature. I did some parallelization in the past in MPI for HPC, and with `multiprocessing` in Python, so maybe I can provide you with some fresh insight on why it does not work properly for the `pd.corr` function.
> 
> It's very interesting because in README there is [API](https://github.com/dubovikmaster/parallel-pandas#api) part with all of supported methods))

I am sorry for my ignorance, I did not see the extensive list of supported functions, and that `.corr()` is not supported, my bad

**Comment by mikbuch** [comment]
Hi Pavel, thank you! I admire your determination. From time to time I and my time are calculating correlations, e.g., for intercorrelation of variables, so this will definitely come it handy!
