### ISSUE TITLE
Strange memory issue

### ISSUE THREAD

**Issue by mirix** [dubovikmaster/parallel-pandas#6]
I have 256 GB of RAM and a dataset with 13m+ rows.

I am applying a complex function to all columns using p_applymap. 

As I was having memory issues I split the df in 117 chunks of ca. 100k rows each.

The first 115 chunks run without issues, but chunk 116 (which is virtually identical to the rest), uses all the available memory until it is killed by the OS. 

Changing the number of processes does not help.

Naturally, I assumed that there was an issue with some of the rows in that chunk, but I could not find anything. 

Furthermore, if I apply the function row by row with p_apply and lambda to that chunk, there are no issues.

Also pandas map works just fine.

Could this be the result of a memory leak? 

Any thoughts?

**Comment by mirix** [comment]
The problem was in the data. Special characters.

**Comment by dubovikmaster** [comment]
Thank you very much for showing interest in my project
Please tell me, does using parallel methods help you in the end?

**Comment by mirix** [comment]
Yes, it helps a lot.

For purely numerical functions I tend to use cudf and similar. 

The good thing about your approach, though, is that it is very much function-agnostic. You just replace the apply or map functions and, typically, it just works.

I have tried many things (modin, pandarallel, dask, etc) and your approach seems to be the most universal and trouble-free.

I have a machine with 48 virtual cores and the difference, as you can imagine, is huge. Being able to harvest all that power with just a few cosmetic changes on my old code and zero learning curve is priceless.

Thanks a bunch!

Ed
